CREATE DATABASE  IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test`;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `name` varchar(25) NOT NULL,
  `age` int(3) NOT NULL,
  `isAdmin` bit(1) NOT NULL,
  `createdDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

LOCK TABLES `users` WRITE;
ALTER TABLE `users` DISABLE KEYS;
INSERT INTO `users` VALUES (1,'Nazjara',23,'','2016-04-27 18:01:19'),(2,'Oksi',24,'','2016-04-27 18:01:26'),(3,'Guest',42,'\0','2016-04-27 18:01:55');
ALTER TABLE `users` ENABLE KEYS ;
UNLOCK TABLES;
